### ISSUE TITLE
Create global css for standard stylings.

### ISSUE THREAD

**Issue by GillaArun** [c2siorg/Webiu#36] opened 2024-07-15 17:13 UTC
**Describe the bug**
Create global css for standard stylings

**Comment by ritankarsaha** [comment] 2024-08-28 12:48
Hello @GillaArun , I would like to work on this issue. I have already thought of some standard css golbal stylings for this, and would like to implement the same. Would you kindly assign this isstue to me? Thanks for the consideration

**Comment by Maahi10001** [comment] 2024-08-29 14:17
> Hello @GillaArun , I would like to work on this issue. I have already thought of some standard css golbal stylings for this, and would like to implement the same. Would you kindly assign this isstue to me? Thanks for the consideration

hey, issues are still work in progress you can start working on available issues immediately aftet GSOC 2024  is done

**Comment by ritankarsaha** [comment] 2024-08-29 17:53
> > Hello @GillaArun , I would like to work on this issue. I have already thought of some standard css golbal stylings for this, and would like to implement the same. Would you kindly assign this isstue to me? Thanks for the consideration
> 
> hey, issues are still work in progress you can start working on available issues immediately aftet GSOC 2024 is done

Oh I'm sorry, actually I picked up this issue because this wasn't currenttly assigned to anyone under the GSOC tag. So I. thought this might be a stand-alone issue not assigned to anyone. Apologies for my mistake. If this issue is still present after the completion of the program I would like to work on this. Thank you for your consideration.

**Comment by ritankarsaha** [comment] 2024-08-29 17:53
> > Hello @GillaArun , I would like to work on this issue. I have already thought of some standard css golbal stylings for this, and would like to implement the same. Would you kindly assign this isstue to me? Thanks for the consideration
> 
> hey, issues are still work in progress you can start working on available issues immediately aftet GSOC 2024 is done

Oh I'm sorry, actually I picked up this issue because this wasn't currenttly assigned to anyone under the GSOC tag. So I. thought this might be a stand-alone issue not assigned to anyone. Apologies for my mistake. If this issue is still present after the completion of the program I would like to work on this. Thank you for your consideration.

**Comment by Maahi10001** [comment] 2024-09-15 15:25
> > > Hello @GillaArun , I would like to work on this issue. I have already thought of some standard css golbal stylings for this, and would like to implement the same. Would you kindly assign this isstue to me? Thanks for the consideration
> > 
> > 
> > hey, issues are still work in progress you can start working on available issues immediately aftet GSOC 2024 is done
> 
> Oh I'm sorry, actually I picked up this issue because this wasn't currenttly assigned to anyone under the GSOC tag. So I. thought this might be a stand-alone issue not assigned to anyone. Apologies for my mistake. If this issue is still present after the completion of the program I would like to work on this. Thank you for your consideration.

@ritankarsaha  am assigning issue to you , you can work on it

**Comment by ritankarsaha** [comment] 2024-09-16 05:24
> > > > Hello @GillaArun , I would like to work on this issue. I have already thought of some standard css golbal stylings for this, and would like to implement the same. Would you kindly assign this isstue to me? Thanks for the consideration
> > > 
> > > 
> > > hey, issues are still work in progress you can start working on available issues immediately aftet GSOC 2024 is done
> > 
> > 
> > Oh I'm sorry, actually I picked up this issue because this wasn't currenttly assigned to anyone under the GSOC tag. So I. thought this might be a stand-alone issue not assigned to anyone. Apologies for my mistake. If this issue is still present after the completion of the program I would like to work on this. Thank you for your consideration.
> 
> @ritankarsaha am assigning issue to you , you can work on it

Sure @GillaArun . Thanks

**Comment by ritankarsaha** [comment] 2024-09-17 20:35
@Maahi10001 I have been facing some issues while cloning this project after forking it. I resolved most of them, however there is a python dependency issue specifically which can't be resolved. I am using a MacOS. Any suggestions on how to troubleshoot this and set this up? Thank You.

**Comment by AEYF-12** [comment] 2024-09-21 14:09
@Maahi10001 I would like to work on this if the issue is not fixed yet. I have the idea to solve it, Thank you for your consideration

**Comment by ritankarsaha** [comment] 2024-09-25 08:57
> @Maahi10001 I would like to work on this if the issue is not fixed yet. I have the idea to solve it, Thank you for your consideration

If you have been able to successfully clone and run this repo on your local system, would you kindly share the steps? I have been facing an issue in a Python dependency. Also I have been using `legacy-peer` dependencies for the node-modules. Would you kindly share the steps? Thank you.

**Comment by rajutkarsh07** [comment] 2024-10-13 08:22
@ritankarsaha for this project go to the feature/webiu-2024 branch and then try to setup it

**Comment by mahmoodalisha** [comment] 2024-10-14 19:01
I have successfully cloned and set up the project locally. I am eager to work on this issue and submit a pull request. I look forward to contributing to this project.

**Comment by ritankarsaha** [comment] 2024-10-15 06:31
> assigning this issue to @mahmoodalisha as @ritankarsaha is inactive

I have solved the issue, was facing problems earlier in setup, but successfully fixed it. I will be reviewing it once more and pushing a PR tonight.

Thanks.

**Comment by rajutkarsh07** [comment] 2024-10-15 07:22
@ritankarsaha assigning this to you but next time be responsive

**Comment by ritankarsaha** [comment] 2024-10-15 07:27
> @ritankarsaha assigning this to you but next time be responsive 
> 

Sorry sir.

**Comment by ritankarsaha** [comment] 2024-10-15 21:46
@rajutkarsh07 
I have been receiving permission issues while pushing my changes. Is there any permission error?

```bash
ritankarsaha@Ritankars-MacBook-Pro webiu-ui % git push origin global-css-for-standard-stylings
remote: Permission to c2siorg/Webiu.git denied to ritankarsaha.
fatal: unable to access 'https://github.com/c2siorg/Webiu.git/': The requested URL returned error: 403
```

Could you please look into this once?

**Comment by rajutkarsh07** [comment] 2024-10-15 21:56
@ritankarsaha you have to fork the repo to contribute you can't directly push into the main c2si repo

**Comment by ritankarsaha** [comment] 2024-10-15 22:51
@rajutkarsh07  @Maahi10001 I have created the global css files for standard stylings in the website. Please let me know if any more modifications/additions are required. I have done all modifications extensively and I hope this global css would be enough for making standard stylings in this website.

Thank You.

**Closed** 2024-11-02 08:12 UTC
Labels: enhancement, good first issue, GSOC-2024
